language: csharp
mono:
  - latest

solution: ProtocolModern.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore ProtocolModern.sln

script:
  - xbuild /p:Configuration=Release ProtocolModern.sln
  - xbuild /p:Configuration=Debug ProtocolModern.sln

notifications:
  email:
    on_success: always
